apm-server:
  host: "0.0.0.0:8200" #Donde estara escuchando el APM server

#Hacia donde enviara la información
output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "apm_system"
  password: "${APM_SYSTEM_PASSWORD}"

setup.kibana:
  host: "kibana:5601"
  username: "apm_system"
  password: "${ELASTIC_PASSWORD}"

logging.level: info
logging.to_files: false